#!/bin/sh

WORKSPACES=$(hyprctl workspaces | awk '/workspace/ {print $3}' 2> /dev/null)

declare -a ACTIVE_LIST=()
declare -a OTHER_LIST=()
declare -A WSP

PREDEFINED_WORKSPACES=(1 2 3 11 12 13)

for i in "${PREDEFINED_WORKSPACES[@]}"; do
  ACTIVE_LIST+=($i)
  WSP[$i]=0
done

for i in $WORKSPACES; do
  if [[ " ${ACTIVE_LIST[@]} " =~ " $i " ]]; then
    WSP[$i]=1
  else
    OTHER_LIST+=($i)
    WSP[$i]=1
  fi
done

for i in $WORKSPACES; do
  WINDOWS=$(hyprctl clients | grep -c "workspace $i")

  if [[ $WINDOWS -gt 0 ]]; then
    WSP[$i]=1
  else
    WSP[$i]=0
  fi
done

OUTPUT="{"
for i in "${!WSP[@]}"; do
  OUTPUT+="\"$i\": ${WSP[$i]},"
done

OUTPUT="${OUTPUT%,}}"
echo "$OUTPUT" | jq .
