general.import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
# normal.family = "Monospace"  # Temel bir font
size = 10  # İhtiyacınıza göre boyutu ayarlayın

# Alternatif olarak Courier New fontunu kullanabilirsiniz
normal.family = "Source Code Pro"

