import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

#[font]
#normal.family = "MesloLGS Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font SemBd"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
#regular
[font]
size = 10

#for video
# size = 35.0
